OBJS=pow3 pow3b sqrt1 sqrt2 sqrt3 sqrt4 loop1 loop2
PHONY+=clean

all: pow3 pow3b sqrt1 sqrt2 sqrt3 sqrt4 loop1 loop2

pow3: pow3.cpp
pow3b: pow3b.cpp
sqrt1: sqrt1.cpp
sqrt2: sqrt2.cpp
sqrt3: sqrt3.cpp
sqrt4: sqrt4.cpp
loop1: loop1.cpp
loop2: loop2.cpp
#unruh: unruh.cpp

.PHONY: $(PHONY)
clean:
	rm $(OBJS)
