OBJS=refmemtest truletest countingptrtest
PHONY+=clean

all: refmemtest truletest countingptrtest

refmemtest: refmemtest.cpp
truletest: truletest.cpp
countingptrtest: countingptrtest.cpp

.PHONY: $(PHONY)
clean:
	rm $(OBJS)
