OBJS=ebco1 ebco2 testcounter virtual

PHONY+=clean

all: ebco1 ebco2 testcounter virtual

ebco1: ebco1.cpp
ebco2: ebco2.cpp
testcounter: testcounter.cpp
virtual: virtual.cpp

.PHONY: $(PHONY)
clean:
	rm $(OBJS)
