OBJS=accum1 accum2 accum5 accum6 accum7 sizeof elementtype isclasst rparam1 rparam2

PHONY+=clean

all: accum1 accum2 accum5 accum6 accum7 sizeof elementtype isclasst rparam1 rparam2

accum1: accum1.cpp
accum2: accum2.cpp
accum5: accum5.cpp
accum6: accum6.cpp
accum7: accum7.cpp
sizeof: sizeof.cpp
elementtype: elementtype.cpp
isclasst: isclasst.cpp
#apply1: apply1.cpp
rparam1: rparam1.cpp
rparam2: rparam2.cpp


.PHONY: $(PHONY)
clean:
	rm $(OBJS)
