OBJS=compose1 compose2 compose3 compose4 compose5 compose6 bindtest
PHONY+=clean

all: compose1 compose2 compose3 compose4 compose5 compose6 bindtest

compose1: compose1.cpp
compose2: compose2.cpp
compose3: compose3.cpp
compose4: compose4.cpp
compose5: compose5.cpp
compose6: compose6.cpp
bindtest: bindtest.cpp
funcptr: funcptr.cpp
functor1: functor1.cpp
functordemo: functordemo.cpp
functorops: functorops.cpp
funcwrap: funcwrap.cpp

.PHONY: $(PHONY)
clean:
	rm $(OBJS)
